-- Database updates for employee salary structures

USE ca_firm_crm;

ALTER TABLE employees 
ADD COLUMN basic DECIMAL(10,2) NOT NULL DEFAULT 0.00 AFTER salary,
ADD COLUMN hra DECIMAL(10,2) NOT NULL DEFAULT 0.00 AFTER basic,
ADD COLUMN conveyance DECIMAL(10,2) NOT NULL DEFAULT 0.00 AFTER hra,
ADD COLUMN allowance DECIMAL(10,2) NOT NULL DEFAULT 0.00 AFTER conveyance,
ADD COLUMN pf DECIMAL(10,2) NOT NULL DEFAULT 0.00 AFTER allowance,
ADD COLUMN pt DECIMAL(10,2) NOT NULL DEFAULT 0.00 AFTER pf,
ADD COLUMN tds DECIMAL(10,2) NOT NULL DEFAULT 0.00 AFTER pt;
